pipeline{
    agent any 
    stages{
        stage('image_build'){
            steps{
                sh '''
                    echo "buildinng image"
                    docker image build -t image6 ${WORKSPACE}/docker
                    '''
            }
        }
        stage('image_tagging'){
            steps{
                sh '''
                    echo "taggig image"
                    docker image tag image6:latest ranjana000/image6:latest
                    '''
            }
        }
        stage('image_push'){
            steps{
                sh '''
                    docker login -u ranjana000 -p shrinidhi@1
                    docker image push ranjana000/image6:latest
                    '''
            }
        }
        stage('deploy'){
            steps{
                sh '''
                    echo "creating container..."
                    docker container run -d --name c6 ranjana000/image6:latest bash
                    '''
            }
        }
    }
}
