pipeline{
    agent any 
    stages{
        stage('image_build'){
            steps{
                sh '''
                    echo "buildinng image"
                    docker image build -t pipimg ${WORKSPACE}/docker
                    '''
            }
        }
        stage('image_tagging'){
            steps{
                sh '''
                    echo "taggig image"
                    docker image tag pipimg:latest ranjana000/pipimg:latest
                    '''
            }
        }
        stage('image_push'){
            steps{
                sh '''
                    docker login -u ranjana000 -p shrinidhi@1
                    docker image push ranjana000/pipimg:latest
                    '''
            }
        }
        stage('deploy'){
            steps{
                sh '''
                    echo "creating container..."
                    docker container run -d --name container1 ranjana000/pipimg:latest bash
                    '''
            }
        }
    }
}
