pipeline{
    agent any
    environment {
        PATH = "$PATH:/usr/share/maven"
    }
    stages{
       stage('image_build'){
            steps{
                sh '''
                    echo "buildinng image"
                    docker image build -t image2 ${WORKSPACE}/docker
                    '''
            }
        }
        stage('Build'){
            steps{
                sh 'mvn clean package'
            }
        }
        stage('SonarQube analysis') {
            steps{
                withSonarQubeEnv('sonarqube-server'){
                sh 'mvn clean install sonar:sonar -Dsonar.projectKey=NewProject'
                sh "mvn sonar:sonar"
                }
            }
        }
        stage('image_tagging'){
            steps{
                sh '''
                    echo "taggig image"
                    docker image tag image2:latest ranjana000/image2:latest
                    '''
            }
        }
        stage('image_push'){
            steps{
                sh '''
                    docker login -u ranjana000 -p shrinidhi@1
                    docker image push ranjana000/image2:latest
                    '''
            }
        }
        stage('deploy'){
             steps{
                sh '''
                    echo "creating container..."
                    docker container run -d --name container2 ranjana000/image2:latest bash
                    '''
            }
        }
    }
}

