pipeline{
    agent any
    environment {
        PATH = "$PATH:/usr/share/maven"
    }
    stages{
        stage('Compile'){
            steps{
                sh 'mvn clean package'
            }
        }
        stage('SonarQube analysis') {
            steps{
                withSonarQubeEnv('sonarqube-server'){
                sh 'mvn clean install sonar:sonar -Dsonar.projectKey=project1'
                sh 'sonarqube-scanner'
                }
            }
        }
        stage('OwASP_SCAN'){
            steps{
                dependencyCheck additionalArguments:' --scan ./ ', odcInstallation: 'DP-check'
                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            }
        }
        stage('image_build'){
            steps{
                sh '''
                    echo "buildinng image"
                    docker image build -t newimg ${WORKSPACE}/docker
                    '''
            }
        }


        stage('image_tagging'){
            steps{
                sh '''
                    echo "taggig image"
                    docker image tag newimg:latest ranjana000/newimg:latest
                    '''
            }
        }
        stage('image_push'){
            steps{
                sh '''
                    docker login -u ranjana000 -p shrinidhi@1
                    docker image push ranjana000/newimg:latest
                    '''
            }
        }
        stage('TRIVY'){
            steps{
                sh " trivy image  ranjana000/newimg:latest "

            }
        }
        stage('deploy k8's'){
             steps{
                script{
                     kubernetesDeploy(config: "deploymentservice.yml", kubeconfigId: "kubernetes")
                }
            }
        }
    }
}
