pipeline{
    agent any
    environment {
        PATH = "$PATH:/usr/share/maven"
    }
    stages{
        stage('Compile'){
            steps{
                sh 'mvn clean package'
            }
        }
        stage('SonarQube analysis') {
            steps{
                withSonarQubeEnv('sonarqube-server'){
                sh 'mvn clean install sonar:sonar -Dsonar.projectKey=project1'
                }
            }
        }
        stage('OwASP_SCAN'){
            steps{
                dependencyCheck additionalArguments:' --scan ./ ', odcInstallation: 'DP-check'
                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            }
        }
        stage('image_build'){
            steps{
                sh '''
                    echo "buildinng image"
                    docker image build -t sonarimage ${WORKSPACE}/docker
                    '''
            }
        }


        stage('image_tagging'){
            steps{
                sh '''
                    echo "taggig image"
                    docker image tag sonarimage:latest ranjana000/sonarimage:latest
                    '''
            }
        }
        stage('image_push'){
            steps{
                sh '''
                    docker login -u ranjana000 -p shrinidhi@1
                    docker image push ranjana000/sonarimage:latest
                    '''
            }
        }
        stage('TRIVY'){
            steps{
                sh " trivy image  ranjana000/sonarimage:latest "

            }
        }
        stage('deploy'){
             steps{
                sh '''
                    echo "creating container..."
                    docker container run -d --name app1 -p 8082:8082 ranjana000/sonarimage:latest bash
                    '''
            }
        }
    }
}
